### ISSUE TITLE
Difference and control returned record

### ISSUE THREAD

**Issue by konradbeck-creditech** [ipavlic/apex-lambda#10]
Hi Ilija,

I have a scenario where I would like to determine the record returned when working out the difference between two lists, i.e the record having the min of a field value compared.

What do you think would be a good approach to solving this or do you think I should compare the lists twice and manage the minimum of the two outside of the compare. An idea I had was perhaps a similar approach to mapAll(SObjectToSObjectFunction fn), or perhaps something entirely different?

Amazing work btw, one of my favorite projects!

**Comment by ipavlic** [comment]
Hi Konrad, thanks. I understand that you would like to check which list has a smaller `min` value. I don't see an issue with having two `Collection` instances to get two minimum values and then comparing between then as you suggest.

I also don't see a problem with combining them into a new list and then finding the minimum of that one combined list. I may be missing some important information.
