### ISSUE TITLE
How would i use this as an ISV?

### ISSUE THREAD

**Issue by az-oolloow** [ipavlic/apex-lambda#7]
Suppose i am developing a managed package for App Exchange.

How would i include the apex-lambda code with that as a dependency?
Do i need to deploy all the classes to my dev org and then ship inside my package?

**Comment by ipavlic** [comment]
Yes. Attribute as required in appropriate location.

**Comment by az-oolloow** [comment]
Ok. this sounds a fair bit suboptimal coz then the dependencies are counted towards apex limits in the org :/

**Comment by ipavlic** [comment]
I believe that measly 30,757 characters spent for this library will ultimately save more elsewhere. If you disagree, you are welcome to fork and remove whatever you do not need. 

I'm also very sorry that you found an open source library written by someone else and freely available for your use not up to your standards. Do you maintain other libraries which passed a security review on AppExchange and are freely available for other people to use?

**Comment by az-oolloow** [comment]
@ipavlic I was not criticizing your work, i am sure it is amazing.
I am new to Salesforce development and i was spoilt by the wonderful world out there that has sorted out dependency management long time ago. I was hoping to discover that i simply don't know how to use it properly, but seems that this dev model is, indeed, what it is.

Again, that was not critical of any work that you do.
