### ISSUE TITLE
Unlocked Package and CI

### ISSUE THREAD

**Issue by dlisovsky** [ipavlic/apex-lambda#8]
Hi @ipavlic - thanks for the great library but it's hard to deploy a lot of classes in different environments.

Is it possible to setup a CI to create the packages? You can migrate the source to DX and create an unlocked package. It still will be open source but it will be much easier to install and upgrade on destination org.

I'm happy to help with DX convert and CI setup, let me know if you are looking forward to the pull request.

Cheers!

**Comment by ipavlic** [comment]
There are two snags:

- the library is not an independent module; it's expected that this code will be used by other code
- DX is not the lowest common denominator for potential users; some might not want to use it

What do you suggest?

**Comment by ipavlic** [comment]
Moved to SFDX.
